parameters:
  assets_directory: '%hidden_directory%/assets'
  build_directory: '%hidden_directory%/build'
  build_filepath: '%hidden_directory%/build.zip'
  cli_configuration_filepath: '%home_directory%/.placeholder/config.json'
  hidden_directory: '%working_directory%/.placeholder'
  project_configuration_filepath: '%working_directory%/placeholder.yml'
  stub_directory: '%application_directory%/stubs'

services:
  _defaults:
    autowire: true
    public: false
    bind:
      string $assetsDirectory: '%assets_directory%'
      string $baseUrl: '%placeholder_api_url%'
      string $buildDirectory: '%build_directory%'
      string $buildFilePath: '%build_filepath%'
      string $homeDirectory: '%home_directory%'
      string $projectDirectory: '%working_directory%'
      string $stubDirectory: '%stub_directory%'

  _instanceof:
    Symfony\Component\Console\Command\Command:
      tags: ['command']

  GuzzleHttp\:
    resource: '../vendor/guzzlehttp/guzzle/src'
    exclude:
      - '../vendor/guzzlehttp/guzzle/src/functions.php'
      - '../vendor/guzzlehttp/guzzle/src/functions_include.php'

  Placeholder\Cli\:
    lazy: true
    resource: '../src'

  Placeholder\Cli\Application:
    public: true
    arguments:
      - !tagged command

  Placeholder\Cli\CliConfiguration:
    arguments:
      $configurationFilePath: '%cli_configuration_filepath%'

  Placeholder\Cli\ProjectConfiguration:
    arguments:
      $configurationFilePath: '%project_configuration_filepath%'

  Placeholder\Cli\Command\Project\BuildProjectCommand:
    arguments:
      $buildSteps:
        - '@Placeholder\Cli\Build\CopyWordPressFilesStep'
        - '@Placeholder\Cli\Build\ModifyWordPressConfigurationStep'
        - '@Placeholder\Cli\Build\ExtractAssetFilesStep'
        - '@Placeholder\Cli\Build\DownloadWpCliStep'
        - '@Placeholder\Cli\Build\EnsurePluginIsInstalledStep'
        - '@Placeholder\Cli\Build\CopyPlaceholderFilesStep'
        - '@Placeholder\Cli\Build\CompressBuildFilesStep'

  Placeholder\Cli\Command\Project\DeployProjectCommand:
    arguments:
      $deploymentSteps:
        - '@Placeholder\Cli\Deployment\UploadBuildStep'
        - '@Placeholder\Cli\Deployment\ProcessAssetsStep'
        - '@Placeholder\Cli\Deployment\StartAndMonitorDeploymentStep'

  Symfony\Component\Filesystem\:
    resource: '../vendor/symfony/filesystem'
