parameters:
  assets_directory: '%hidden_directory%/assets'
  build_directory: '%hidden_directory%/build'
  build_artifact_path: '%hidden_directory%/build.zip'
  cli_configuration_filepath: '%home_directory%/.ymir/config.json'
  hidden_directory: '%working_directory%/.ymir'
  project_configuration_filepath: '%working_directory%/ymir.yml'
  stub_directory: '%application_directory%/stubs'

services:
  _defaults:
    autowire: true
    public: false
    bind:
      string $assetsDirectory: '%assets_directory%'
      string $baseUrl: '%ymir_api_url%'
      string $buildDirectory: '%build_directory%'
      string $buildArtifactPath: '%build_artifact_path%'
      string $hiddenDirectory: '%hidden_directory%'
      string $homeDirectory: '%home_directory%'
      string $projectDirectory: '%working_directory%'
      string $stubDirectory: '%stub_directory%'

  _instanceof:
    Symfony\Component\Console\Command\Command:
      tags: ['command']

  GuzzleHttp\:
    resource: '../vendor/guzzlehttp/guzzle/src'
    exclude:
      - '../vendor/guzzlehttp/guzzle/src/functions.php'
      - '../vendor/guzzlehttp/guzzle/src/functions_include.php'

  Ymir\Cli\:
    lazy: true
    resource: '../src'

  Ymir\Cli\Application:
    public: true
    arguments:
      - !tagged command

  Ymir\Cli\CliConfiguration:
    arguments:
      $configurationFilePath: '%cli_configuration_filepath%'

  Ymir\Cli\ProjectConfiguration:
    arguments:
      $configurationFilePath: '%project_configuration_filepath%'

  Ymir\Cli\Command\Project\BuildProjectCommand:
    arguments:
      $buildSteps:
        - '@Ymir\Cli\Build\CopyWordPressFilesStep'
        - '@Ymir\Cli\Build\DownloadWpCliStep'
        - '@Ymir\Cli\Build\EnsurePluginIsInstalledStep'
        - '@Ymir\Cli\Build\ModifyWordPressConfigurationStep'
        - '@Ymir\Cli\Build\ExtractAssetFilesStep'
        - '@Ymir\Cli\Build\CompressBuildFilesStep'

  Ymir\Cli\Command\Project\DeployProjectCommand:
    arguments:
      $deploymentSteps:
        - '@Ymir\Cli\Deployment\UploadBuildStep'
        - '@Ymir\Cli\Deployment\ProcessAssetsStep'
        - '@Ymir\Cli\Deployment\StartAndMonitorDeploymentStep'
        - '@Ymir\Cli\Deployment\CleanupStep'

  Symfony\Component\Filesystem\:
    resource: '../vendor/symfony/filesystem'
